#!/bin/bash
# if the user has Macbook with amd64, select compatible platform
PLATFORM=""
if PLATFORM=$(arch); then
    if PLATFORM="arm64"; then
        PLATFORM="--platform linux/amd64" 
    fi
fi

docker run --rm \
    $PLATFORM \
    --network=host \
    -u $(id -u):$(id -g) \
    -v $PWD:/work \
    -t torstees/whistle "$@"
